Repository intlify/vite-plugin-vue-i18n, pull requests merged in 2021-03, with the labels that each got.

#69 upgrade deps
  package.json
  yarn.lock
Labels: Type: Improvement

#71 experimental: intlify meta info injection plugin
  src/injection.ts
  test/fixtures/injections/basic.vue
  test/injection.test.ts
  test/utils.ts
Labels: Type: Feature

#75 fix: esm-bundler warning
  src/index.ts
Labels: Type: Bug

#79 fix: add vue-i18n peer dependency
  package.json
Labels: Type: Improvement

#80 fix: suppress console in production
  src/index.ts
Labels: Type: Bug
