Repository intlify/vite-plugin-vue-i18n, pull requests merged in 2021-02, with the labels that each got.

#48 feat: vue-i18n dist module optimization
  README.md
  package.json
  src/index.ts
  test/__snapshots__/custom-block.test.ts.snap
  test/custom-block.test.ts
  test/fixtures/fully-block.vue
  test/utils.ts
  yarn.lock
Labels: Type: Feature

#50 feat: static bundle importing
  README.md
  examples/composition/main.ts
  examples/legacy/main.ts
  package.json
  src/index.ts
  test/bundle-import.test.ts
  test/fixtures/bundle.ts
  test/utils.ts
  yarn.lock
Labels: Type: Feature

#53 fix: cannot install fast-glob
  package.json
Labels: Type: Bug

#56 fix: cannot resolve vue-i18n runtime in monorepo
  package.json
  src/index.ts
  yarn.lock
Labels: Type: Bug

#57 feat: runtimeOnly option
  README.md
  src/index.ts
  src/options.ts
Labels: Type: Feature

#59 fix: alias changed to resolve.alias in latest vite
  README.md
  package.json
  src/index.ts
  test/utils.ts
  yarn.lock
Labels: Type: Improvement

#64 bug: fix cannot resolve.alias for array type
  jest.e2e.config.js
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: Type: Bug

#65 improvement: support client types
  README.md
  client.d.ts
  package.json
Labels: Type: Improvement
