Repository intlify/vite-plugin-vue-i18n, pull requests merged in 2021-01, with the labels that each got.

#27 feat: support vite 2
  .github/workflows/test.yml
  README.md
  examples/composition/package.json
  examples/composition/vite.config.ts
  examples/composition/yarn.lock
  examples/global/package.json
  examples/global/vite.config.ts
  examples/global/yarn.lock
  examples/legacy/package.json
  examples/legacy/vite.config.ts
  examples/legacy/yarn.lock
  package.json
  src/index.ts
  src/query.ts
  src/server.ts
  src/transform.ts
  test/utils.ts
  yarn.lock
Labels: Type: Feature

#31 fix: cannot transform other blocks
  package.json
  src/transform.ts
  test/__snapshots__/custom-block.test.ts.snap
  test/custom-block.test.ts
  test/fixtures/fully-block.vue
  test/utils.ts
  yarn.lock
Labels: Type: Bug

#32 improvement: pre-compilation with vite mode option
  src/index.ts
  src/transform.ts
Labels: Type: Improvement

#36 improvement: json resource handling
  README.md
  package.json
  src/index.ts
Labels: Type: Improvement

#38 improvement: module exporting
  README.md
  examples/composition/package.json
  examples/composition/vite.config.ts
  examples/composition/yarn.lock
  examples/global/package.json
  examples/global/vite.config.ts
  examples/global/yarn.lock
  examples/legacy/package.json
  examples/legacy/vite.config.ts
  examples/legacy/yarn.lock
  examples/vite.config.ts
  package.json
  src/index.ts
  test/utils.ts
  yarn.lock
Labels: Type: Improvement

#40 improvement: support named & default exporting
  README.md
  examples/vite.config.ts
  src/index.ts
  test/utils.ts
Labels: Type: Improvement

#43 breaking: remove runtimeOption
  README.md
  src/index.ts
  src/options.ts
Labels: Type: Breaking

#45 Fix test fail on windows
  src/index.ts
Labels: Type: Bug
